/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginAlunoRouteImport } from './routes/login-aluno'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PortalVideosRouteImport } from './routes/portal/videos'
import { Route as PortalTrocarSenhaRouteImport } from './routes/portal/trocar-senha'
import { Route as PortalPdfRouteImport } from './routes/portal/pdf'
import { Route as PortalMensalidadesRouteImport } from './routes/portal/mensalidades'
import { Route as PainelTrocarSenhaRouteImport } from './routes/painel/trocar-senha'
import { Route as PainelRelatorioRouteImport } from './routes/painel/relatorio'
import { Route as PainelProfessoresRouteImport } from './routes/painel/professores'
import { Route as PainelPagamentosRouteImport } from './routes/painel/pagamentos'
import { Route as PainelFinanceiroRouteImport } from './routes/painel/financeiro'
import { Route as PainelAlunosRouteImport } from './routes/painel/alunos'
import { Route as PainelAgendaRouteImport } from './routes/painel/agenda'
import { Route as PainelDisciplinasDisciplineIdRouteImport } from './routes/painel/disciplinas/$disciplineId'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api/mercadopago/webhook'
import { Route as PainelRelatorioStudentIdPdfRouteImport } from './routes/painel/relatorio/$studentId/pdf'

const LoginAlunoRoute = LoginAlunoRouteImport.update({
  id: '/login-aluno',
  path: '/login-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PortalVideosRoute = PortalVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTrocarSenhaRoute = PortalTrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPdfRoute = PortalPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMensalidadesRoute = PortalMensalidadesRouteImport.update({
  id: '/mensalidades',
  path: '/mensalidades',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PainelTrocarSenhaRoute = PainelTrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelRelatorioRoute = PainelRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelProfessoresRoute = PainelProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelPagamentosRoute = PainelPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelAlunosRoute = PainelAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelDisciplinasDisciplineIdRoute =
  PainelDisciplinasDisciplineIdRouteImport.update({
    id: '/disciplinas/$disciplineId',
    path: '/disciplinas/$disciplineId',
    getParentRoute: () => PainelRouteRoute,
  } as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRelatorioStudentIdPdfRoute =
  PainelRelatorioStudentIdPdfRouteImport.update({
    id: '/$studentId/pdf',
    path: '/$studentId/pdf',
    getParentRoute: () => PainelRelatorioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-aluno': typeof LoginAlunoRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/alunos': typeof PainelAlunosRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/pagamentos': typeof PainelPagamentosRoute
  '/painel/professores': typeof PainelProfessoresRoute
  '/painel/relatorio': typeof PainelRelatorioRouteWithChildren
  '/painel/trocar-senha': typeof PainelTrocarSenhaRoute
  '/portal/mensalidades': typeof PortalMensalidadesRoute
  '/portal/pdf': typeof PortalPdfRoute
  '/portal/trocar-senha': typeof PortalTrocarSenhaRoute
  '/portal/videos': typeof PortalVideosRoute
  '/painel/': typeof PainelIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/painel/disciplinas/$disciplineId': typeof PainelDisciplinasDisciplineIdRoute
  '/painel/relatorio/$studentId/pdf': typeof PainelRelatorioStudentIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-aluno': typeof LoginAlunoRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/alunos': typeof PainelAlunosRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/pagamentos': typeof PainelPagamentosRoute
  '/painel/professores': typeof PainelProfessoresRoute
  '/painel/relatorio': typeof PainelRelatorioRouteWithChildren
  '/painel/trocar-senha': typeof PainelTrocarSenhaRoute
  '/portal/mensalidades': typeof PortalMensalidadesRoute
  '/portal/pdf': typeof PortalPdfRoute
  '/portal/trocar-senha': typeof PortalTrocarSenhaRoute
  '/portal/videos': typeof PortalVideosRoute
  '/painel': typeof PainelIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/painel/disciplinas/$disciplineId': typeof PainelDisciplinasDisciplineIdRoute
  '/painel/relatorio/$studentId/pdf': typeof PainelRelatorioStudentIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-aluno': typeof LoginAlunoRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/alunos': typeof PainelAlunosRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/pagamentos': typeof PainelPagamentosRoute
  '/painel/professores': typeof PainelProfessoresRoute
  '/painel/relatorio': typeof PainelRelatorioRouteWithChildren
  '/painel/trocar-senha': typeof PainelTrocarSenhaRoute
  '/portal/mensalidades': typeof PortalMensalidadesRoute
  '/portal/pdf': typeof PortalPdfRoute
  '/portal/trocar-senha': typeof PortalTrocarSenhaRoute
  '/portal/videos': typeof PortalVideosRoute
  '/painel/': typeof PainelIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/painel/disciplinas/$disciplineId': typeof PainelDisciplinasDisciplineIdRoute
  '/painel/relatorio/$studentId/pdf': typeof PainelRelatorioStudentIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/portal'
    | '/login'
    | '/login-aluno'
    | '/painel/agenda'
    | '/painel/alunos'
    | '/painel/financeiro'
    | '/painel/pagamentos'
    | '/painel/professores'
    | '/painel/relatorio'
    | '/painel/trocar-senha'
    | '/portal/mensalidades'
    | '/portal/pdf'
    | '/portal/trocar-senha'
    | '/portal/videos'
    | '/painel/'
    | '/portal/'
    | '/api/mercadopago/webhook'
    | '/painel/disciplinas/$disciplineId'
    | '/painel/relatorio/$studentId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-aluno'
    | '/painel/agenda'
    | '/painel/alunos'
    | '/painel/financeiro'
    | '/painel/pagamentos'
    | '/painel/professores'
    | '/painel/relatorio'
    | '/painel/trocar-senha'
    | '/portal/mensalidades'
    | '/portal/pdf'
    | '/portal/trocar-senha'
    | '/portal/videos'
    | '/painel'
    | '/portal'
    | '/api/mercadopago/webhook'
    | '/painel/disciplinas/$disciplineId'
    | '/painel/relatorio/$studentId/pdf'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/portal'
    | '/login'
    | '/login-aluno'
    | '/painel/agenda'
    | '/painel/alunos'
    | '/painel/financeiro'
    | '/painel/pagamentos'
    | '/painel/professores'
    | '/painel/relatorio'
    | '/painel/trocar-senha'
    | '/portal/mensalidades'
    | '/portal/pdf'
    | '/portal/trocar-senha'
    | '/portal/videos'
    | '/painel/'
    | '/portal/'
    | '/api/mercadopago/webhook'
    | '/painel/disciplinas/$disciplineId'
    | '/painel/relatorio/$studentId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginAlunoRoute: typeof LoginAlunoRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-aluno': {
      id: '/login-aluno'
      path: '/login-aluno'
      fullPath: '/login-aluno'
      preLoaderRoute: typeof LoginAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/portal/videos': {
      id: '/portal/videos'
      path: '/videos'
      fullPath: '/portal/videos'
      preLoaderRoute: typeof PortalVideosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/trocar-senha': {
      id: '/portal/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/portal/trocar-senha'
      preLoaderRoute: typeof PortalTrocarSenhaRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/pdf': {
      id: '/portal/pdf'
      path: '/pdf'
      fullPath: '/portal/pdf'
      preLoaderRoute: typeof PortalPdfRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/mensalidades': {
      id: '/portal/mensalidades'
      path: '/mensalidades'
      fullPath: '/portal/mensalidades'
      preLoaderRoute: typeof PortalMensalidadesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/painel/trocar-senha': {
      id: '/painel/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/painel/trocar-senha'
      preLoaderRoute: typeof PainelTrocarSenhaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/relatorio': {
      id: '/painel/relatorio'
      path: '/relatorio'
      fullPath: '/painel/relatorio'
      preLoaderRoute: typeof PainelRelatorioRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/professores': {
      id: '/painel/professores'
      path: '/professores'
      fullPath: '/painel/professores'
      preLoaderRoute: typeof PainelProfessoresRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/pagamentos': {
      id: '/painel/pagamentos'
      path: '/pagamentos'
      fullPath: '/painel/pagamentos'
      preLoaderRoute: typeof PainelPagamentosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/alunos': {
      id: '/painel/alunos'
      path: '/alunos'
      fullPath: '/painel/alunos'
      preLoaderRoute: typeof PainelAlunosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/disciplinas/$disciplineId': {
      id: '/painel/disciplinas/$disciplineId'
      path: '/disciplinas/$disciplineId'
      fullPath: '/painel/disciplinas/$disciplineId'
      preLoaderRoute: typeof PainelDisciplinasDisciplineIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/relatorio/$studentId/pdf': {
      id: '/painel/relatorio/$studentId/pdf'
      path: '/$studentId/pdf'
      fullPath: '/painel/relatorio/$studentId/pdf'
      preLoaderRoute: typeof PainelRelatorioStudentIdPdfRouteImport
      parentRoute: typeof PainelRelatorioRoute
    }
  }
}

interface PainelRelatorioRouteChildren {
  PainelRelatorioStudentIdPdfRoute: typeof PainelRelatorioStudentIdPdfRoute
}

const PainelRelatorioRouteChildren: PainelRelatorioRouteChildren = {
  PainelRelatorioStudentIdPdfRoute: PainelRelatorioStudentIdPdfRoute,
}

const PainelRelatorioRouteWithChildren = PainelRelatorioRoute._addFileChildren(
  PainelRelatorioRouteChildren,
)

interface PainelRouteRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelAlunosRoute: typeof PainelAlunosRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelPagamentosRoute: typeof PainelPagamentosRoute
  PainelProfessoresRoute: typeof PainelProfessoresRoute
  PainelRelatorioRoute: typeof PainelRelatorioRouteWithChildren
  PainelTrocarSenhaRoute: typeof PainelTrocarSenhaRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelDisciplinasDisciplineIdRoute: typeof PainelDisciplinasDisciplineIdRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelAlunosRoute: PainelAlunosRoute,
  PainelFinanceiroRoute: PainelFinanceiroRoute,
  PainelPagamentosRoute: PainelPagamentosRoute,
  PainelProfessoresRoute: PainelProfessoresRoute,
  PainelRelatorioRoute: PainelRelatorioRouteWithChildren,
  PainelTrocarSenhaRoute: PainelTrocarSenhaRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelDisciplinasDisciplineIdRoute: PainelDisciplinasDisciplineIdRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalMensalidadesRoute: typeof PortalMensalidadesRoute
  PortalPdfRoute: typeof PortalPdfRoute
  PortalTrocarSenhaRoute: typeof PortalTrocarSenhaRoute
  PortalVideosRoute: typeof PortalVideosRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalMensalidadesRoute: PortalMensalidadesRoute,
  PortalPdfRoute: PortalPdfRoute,
  PortalTrocarSenhaRoute: PortalTrocarSenhaRoute,
  PortalVideosRoute: PortalVideosRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginAlunoRoute: LoginAlunoRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
