/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaAlunoRouteImport } from './routes/redefinir-senha-aluno'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginAlunoRouteImport } from './routes/login-aluno'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaAlunoRouteImport } from './routes/esqueci-senha-aluno'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as AgendaDoticsRouteImport } from './routes/agenda[.]ics'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as SemestreSemesterRouteImport } from './routes/semestre/$semester'
import { Route as PortalVideosRouteImport } from './routes/portal/videos'
import { Route as PortalTrocarSenhaRouteImport } from './routes/portal/trocar-senha'
import { Route as PortalPdfRouteImport } from './routes/portal/pdf'
import { Route as PortalNotasRouteImport } from './routes/portal/notas'
import { Route as PortalMensalidadesRouteImport } from './routes/portal/mensalidades'
import { Route as PortalDiscipuladoRouteImport } from './routes/portal/discipulado'
import { Route as PortalContaRouteImport } from './routes/portal/conta'
import { Route as PainelTrocarSenhaRouteImport } from './routes/painel/trocar-senha'
import { Route as PainelRelatorioModuloRouteImport } from './routes/painel/relatorio-modulo'
import { Route as PainelRelatorioRouteImport } from './routes/painel/relatorio'
import { Route as PainelProfessoresRouteImport } from './routes/painel/professores'
import { Route as PainelPagamentosRouteImport } from './routes/painel/pagamentos'
import { Route as PainelMateriaisRouteImport } from './routes/painel/materiais'
import { Route as PainelFinanceiroRouteImport } from './routes/painel/financeiro'
import { Route as PainelDespesasRouteImport } from './routes/painel/despesas'
import { Route as PainelBibliotecaRouteImport } from './routes/painel/biblioteca'
import { Route as PainelAuditoriaRouteImport } from './routes/painel/auditoria'
import { Route as PainelAlunosRouteImport } from './routes/painel/alunos'
import { Route as PainelAgendaRouteImport } from './routes/painel/agenda'
import { Route as PortalTarefasIndexRouteImport } from './routes/portal/tarefas/index'
import { Route as PortalProvasIndexRouteImport } from './routes/portal/provas/index'
import { Route as PortalForumIndexRouteImport } from './routes/portal/forum/index'
import { Route as PortalDisciplinasIndexRouteImport } from './routes/portal/disciplinas/index'
import { Route as PortalBibliotecaIndexRouteImport } from './routes/portal/biblioteca/index'
import { Route as PortalApostilasIndexRouteImport } from './routes/portal/apostilas/index'
import { Route as PainelTarefasIndexRouteImport } from './routes/painel/tarefas/index'
import { Route as PainelProvasIndexRouteImport } from './routes/painel/provas/index'
import { Route as PainelForumIndexRouteImport } from './routes/painel/forum/index'
import { Route as PainelForumInternoIndexRouteImport } from './routes/painel/forum-interno/index'
import { Route as PortalTarefasAssignmentIdRouteImport } from './routes/portal/tarefas/$assignmentId'
import { Route as PortalProvasExamIdRouteImport } from './routes/portal/provas/$examId'
import { Route as PortalForumThreadIdRouteImport } from './routes/portal/forum/$threadId'
import { Route as PortalDisciplinasDisciplineIdRouteImport } from './routes/portal/disciplinas/$disciplineId'
import { Route as PortalCheckinLessonIdRouteImport } from './routes/portal/checkin/$lessonId'
import { Route as PortalBibliotecaBookIdRouteImport } from './routes/portal/biblioteca/$bookId'
import { Route as PortalApostilasMaterialIdRouteImport } from './routes/portal/apostilas/$materialId'
import { Route as PainelTarefasAssignmentIdRouteImport } from './routes/painel/tarefas/$assignmentId'
import { Route as PainelProvasExamIdRouteImport } from './routes/painel/provas/$examId'
import { Route as PainelForumThreadIdRouteImport } from './routes/painel/forum/$threadId'
import { Route as PainelForumInternoThreadIdRouteImport } from './routes/painel/forum-interno/$threadId'
import { Route as PainelDisciplinasDisciplineIdRouteImport } from './routes/painel/disciplinas/$disciplineId'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api/mercadopago/webhook'
import { Route as ApiCronPaymentRemindersRouteImport } from './routes/api/cron/payment-reminders'
import { Route as ApiCronFinalizeExpiredExamsRouteImport } from './routes/api/cron/finalize-expired-exams'
import { Route as ApiBlobUploadRouteImport } from './routes/api/blob/upload'
import { Route as PortalMensalidadesChargeIdReciboRouteImport } from './routes/portal/mensalidades/$chargeId/recibo'
import { Route as PainelRelatorioStudentIdPdfRouteImport } from './routes/painel/relatorio/$studentId/pdf'
import { Route as PainelPagamentosChargeIdReciboRouteImport } from './routes/painel/pagamentos/$chargeId/recibo'
import { Route as PainelRelatorioTurmaDisciplineIdPdfRouteImport } from './routes/painel/relatorio/turma/$disciplineId/pdf'

const RedefinirSenhaAlunoRoute = RedefinirSenhaAlunoRouteImport.update({
  id: '/redefinir-senha-aluno',
  path: '/redefinir-senha-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAlunoRoute = LoginAlunoRouteImport.update({
  id: '/login-aluno',
  path: '/login-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaAlunoRoute = EsqueciSenhaAlunoRouteImport.update({
  id: '/esqueci-senha-aluno',
  path: '/esqueci-senha-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaDoticsRoute = AgendaDoticsRouteImport.update({
  id: '/agenda.ics',
  path: '/agenda.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const SemestreSemesterRoute = SemestreSemesterRouteImport.update({
  id: '/semestre/$semester',
  path: '/semestre/$semester',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalVideosRoute = PortalVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalTrocarSenhaRoute = PortalTrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalPdfRoute = PortalPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalNotasRoute = PortalNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMensalidadesRoute = PortalMensalidadesRouteImport.update({
  id: '/mensalidades',
  path: '/mensalidades',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDiscipuladoRoute = PortalDiscipuladoRouteImport.update({
  id: '/discipulado',
  path: '/discipulado',
  getParentRoute: () => PortalRouteRoute,
} as any).lazy(() =>
  import('./routes/portal/discipulado.lazy').then((d) => d.Route),
)
const PortalContaRoute = PortalContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PainelTrocarSenhaRoute = PainelTrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelRelatorioModuloRoute = PainelRelatorioModuloRouteImport.update({
  id: '/relatorio-modulo',
  path: '/relatorio-modulo',
  getParentRoute: () => PainelRouteRoute,
} as any).lazy(() =>
  import('./routes/painel/relatorio-modulo.lazy').then((d) => d.Route),
)
const PainelRelatorioRoute = PainelRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => PainelRouteRoute,
} as any).lazy(() =>
  import('./routes/painel/relatorio.lazy').then((d) => d.Route),
)
const PainelProfessoresRoute = PainelProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelPagamentosRoute = PainelPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelMateriaisRoute = PainelMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelFinanceiroRoute = PainelFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelDespesasRoute = PainelDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelBibliotecaRoute = PainelBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelAuditoriaRoute = PainelAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => PainelRouteRoute,
} as any).lazy(() =>
  import('./routes/painel/auditoria.lazy').then((d) => d.Route),
)
const PainelAlunosRoute = PainelAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PortalTarefasIndexRoute = PortalTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalProvasIndexRoute = PortalProvasIndexRouteImport.update({
  id: '/provas/',
  path: '/provas/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalForumIndexRoute = PortalForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDisciplinasIndexRoute = PortalDisciplinasIndexRouteImport.update({
  id: '/disciplinas/',
  path: '/disciplinas/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalBibliotecaIndexRoute = PortalBibliotecaIndexRouteImport.update({
  id: '/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalApostilasIndexRoute = PortalApostilasIndexRouteImport.update({
  id: '/apostilas/',
  path: '/apostilas/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PainelTarefasIndexRoute = PainelTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelProvasIndexRoute = PainelProvasIndexRouteImport.update({
  id: '/provas/',
  path: '/provas/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelForumIndexRoute = PainelForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelForumInternoIndexRoute = PainelForumInternoIndexRouteImport.update({
  id: '/forum-interno/',
  path: '/forum-interno/',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PortalTarefasAssignmentIdRoute =
  PortalTarefasAssignmentIdRouteImport.update({
    id: '/tarefas/$assignmentId',
    path: '/tarefas/$assignmentId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProvasExamIdRoute = PortalProvasExamIdRouteImport.update({
  id: '/provas/$examId',
  path: '/provas/$examId',
  getParentRoute: () => PortalRouteRoute,
} as any).lazy(() =>
  import('./routes/portal/provas/$examId.lazy').then((d) => d.Route),
)
const PortalForumThreadIdRoute = PortalForumThreadIdRouteImport.update({
  id: '/forum/$threadId',
  path: '/forum/$threadId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDisciplinasDisciplineIdRoute =
  PortalDisciplinasDisciplineIdRouteImport.update({
    id: '/disciplinas/$disciplineId',
    path: '/disciplinas/$disciplineId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalCheckinLessonIdRoute = PortalCheckinLessonIdRouteImport.update({
  id: '/checkin/$lessonId',
  path: '/checkin/$lessonId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalBibliotecaBookIdRoute = PortalBibliotecaBookIdRouteImport.update({
  id: '/biblioteca/$bookId',
  path: '/biblioteca/$bookId',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalApostilasMaterialIdRoute =
  PortalApostilasMaterialIdRouteImport.update({
    id: '/apostilas/$materialId',
    path: '/apostilas/$materialId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PainelTarefasAssignmentIdRoute =
  PainelTarefasAssignmentIdRouteImport.update({
    id: '/tarefas/$assignmentId',
    path: '/tarefas/$assignmentId',
    getParentRoute: () => PainelRouteRoute,
  } as any).lazy(() =>
    import('./routes/painel/tarefas/$assignmentId.lazy').then((d) => d.Route),
  )
const PainelProvasExamIdRoute = PainelProvasExamIdRouteImport.update({
  id: '/provas/$examId',
  path: '/provas/$examId',
  getParentRoute: () => PainelRouteRoute,
} as any).lazy(() =>
  import('./routes/painel/provas/$examId.lazy').then((d) => d.Route),
)
const PainelForumThreadIdRoute = PainelForumThreadIdRouteImport.update({
  id: '/forum/$threadId',
  path: '/forum/$threadId',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelForumInternoThreadIdRoute =
  PainelForumInternoThreadIdRouteImport.update({
    id: '/forum-interno/$threadId',
    path: '/forum-interno/$threadId',
    getParentRoute: () => PainelRouteRoute,
  } as any)
const PainelDisciplinasDisciplineIdRoute =
  PainelDisciplinasDisciplineIdRouteImport.update({
    id: '/disciplinas/$disciplineId',
    path: '/disciplinas/$disciplineId',
    getParentRoute: () => PainelRouteRoute,
  } as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPaymentRemindersRoute = ApiCronPaymentRemindersRouteImport.update({
  id: '/api/cron/payment-reminders',
  path: '/api/cron/payment-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFinalizeExpiredExamsRoute =
  ApiCronFinalizeExpiredExamsRouteImport.update({
    id: '/api/cron/finalize-expired-exams',
    path: '/api/cron/finalize-expired-exams',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBlobUploadRoute = ApiBlobUploadRouteImport.update({
  id: '/api/blob/upload',
  path: '/api/blob/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMensalidadesChargeIdReciboRoute =
  PortalMensalidadesChargeIdReciboRouteImport.update({
    id: '/$chargeId/recibo',
    path: '/$chargeId/recibo',
    getParentRoute: () => PortalMensalidadesRoute,
  } as any)
const PainelRelatorioStudentIdPdfRoute =
  PainelRelatorioStudentIdPdfRouteImport.update({
    id: '/$studentId/pdf',
    path: '/$studentId/pdf',
    getParentRoute: () => PainelRelatorioRoute,
  } as any)
const PainelPagamentosChargeIdReciboRoute =
  PainelPagamentosChargeIdReciboRouteImport.update({
    id: '/$chargeId/recibo',
    path: '/$chargeId/recibo',
    getParentRoute: () => PainelPagamentosRoute,
  } as any)
const PainelRelatorioTurmaDisciplineIdPdfRoute =
  PainelRelatorioTurmaDisciplineIdPdfRouteImport.update({
    id: '/turma/$disciplineId/pdf',
    path: '/turma/$disciplineId/pdf',
    getParentRoute: () => PainelRelatorioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/agenda.ics': typeof AgendaDoticsRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/esqueci-senha-aluno': typeof EsqueciSenhaAlunoRoute
  '/login': typeof LoginRoute
  '/login-aluno': typeof LoginAlunoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/redefinir-senha-aluno': typeof RedefinirSenhaAlunoRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/alunos': typeof PainelAlunosRoute
  '/painel/auditoria': typeof PainelAuditoriaRoute
  '/painel/biblioteca': typeof PainelBibliotecaRoute
  '/painel/despesas': typeof PainelDespesasRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/materiais': typeof PainelMateriaisRoute
  '/painel/pagamentos': typeof PainelPagamentosRouteWithChildren
  '/painel/professores': typeof PainelProfessoresRoute
  '/painel/relatorio': typeof PainelRelatorioRouteWithChildren
  '/painel/relatorio-modulo': typeof PainelRelatorioModuloRoute
  '/painel/trocar-senha': typeof PainelTrocarSenhaRoute
  '/portal/conta': typeof PortalContaRoute
  '/portal/discipulado': typeof PortalDiscipuladoRoute
  '/portal/mensalidades': typeof PortalMensalidadesRouteWithChildren
  '/portal/notas': typeof PortalNotasRoute
  '/portal/pdf': typeof PortalPdfRoute
  '/portal/trocar-senha': typeof PortalTrocarSenhaRoute
  '/portal/videos': typeof PortalVideosRoute
  '/semestre/$semester': typeof SemestreSemesterRoute
  '/painel/': typeof PainelIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/api/cron/finalize-expired-exams': typeof ApiCronFinalizeExpiredExamsRoute
  '/api/cron/payment-reminders': typeof ApiCronPaymentRemindersRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/painel/disciplinas/$disciplineId': typeof PainelDisciplinasDisciplineIdRoute
  '/painel/forum-interno/$threadId': typeof PainelForumInternoThreadIdRoute
  '/painel/forum/$threadId': typeof PainelForumThreadIdRoute
  '/painel/provas/$examId': typeof PainelProvasExamIdRoute
  '/painel/tarefas/$assignmentId': typeof PainelTarefasAssignmentIdRoute
  '/portal/apostilas/$materialId': typeof PortalApostilasMaterialIdRoute
  '/portal/biblioteca/$bookId': typeof PortalBibliotecaBookIdRoute
  '/portal/checkin/$lessonId': typeof PortalCheckinLessonIdRoute
  '/portal/disciplinas/$disciplineId': typeof PortalDisciplinasDisciplineIdRoute
  '/portal/forum/$threadId': typeof PortalForumThreadIdRoute
  '/portal/provas/$examId': typeof PortalProvasExamIdRoute
  '/portal/tarefas/$assignmentId': typeof PortalTarefasAssignmentIdRoute
  '/painel/forum-interno/': typeof PainelForumInternoIndexRoute
  '/painel/forum/': typeof PainelForumIndexRoute
  '/painel/provas/': typeof PainelProvasIndexRoute
  '/painel/tarefas/': typeof PainelTarefasIndexRoute
  '/portal/apostilas/': typeof PortalApostilasIndexRoute
  '/portal/biblioteca/': typeof PortalBibliotecaIndexRoute
  '/portal/disciplinas/': typeof PortalDisciplinasIndexRoute
  '/portal/forum/': typeof PortalForumIndexRoute
  '/portal/provas/': typeof PortalProvasIndexRoute
  '/portal/tarefas/': typeof PortalTarefasIndexRoute
  '/painel/pagamentos/$chargeId/recibo': typeof PainelPagamentosChargeIdReciboRoute
  '/painel/relatorio/$studentId/pdf': typeof PainelRelatorioStudentIdPdfRoute
  '/portal/mensalidades/$chargeId/recibo': typeof PortalMensalidadesChargeIdReciboRoute
  '/painel/relatorio/turma/$disciplineId/pdf': typeof PainelRelatorioTurmaDisciplineIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda.ics': typeof AgendaDoticsRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/esqueci-senha-aluno': typeof EsqueciSenhaAlunoRoute
  '/login': typeof LoginRoute
  '/login-aluno': typeof LoginAlunoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/redefinir-senha-aluno': typeof RedefinirSenhaAlunoRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/alunos': typeof PainelAlunosRoute
  '/painel/auditoria': typeof PainelAuditoriaRoute
  '/painel/biblioteca': typeof PainelBibliotecaRoute
  '/painel/despesas': typeof PainelDespesasRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/materiais': typeof PainelMateriaisRoute
  '/painel/pagamentos': typeof PainelPagamentosRouteWithChildren
  '/painel/professores': typeof PainelProfessoresRoute
  '/painel/relatorio': typeof PainelRelatorioRouteWithChildren
  '/painel/relatorio-modulo': typeof PainelRelatorioModuloRoute
  '/painel/trocar-senha': typeof PainelTrocarSenhaRoute
  '/portal/conta': typeof PortalContaRoute
  '/portal/discipulado': typeof PortalDiscipuladoRoute
  '/portal/mensalidades': typeof PortalMensalidadesRouteWithChildren
  '/portal/notas': typeof PortalNotasRoute
  '/portal/pdf': typeof PortalPdfRoute
  '/portal/trocar-senha': typeof PortalTrocarSenhaRoute
  '/portal/videos': typeof PortalVideosRoute
  '/semestre/$semester': typeof SemestreSemesterRoute
  '/painel': typeof PainelIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/api/cron/finalize-expired-exams': typeof ApiCronFinalizeExpiredExamsRoute
  '/api/cron/payment-reminders': typeof ApiCronPaymentRemindersRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/painel/disciplinas/$disciplineId': typeof PainelDisciplinasDisciplineIdRoute
  '/painel/forum-interno/$threadId': typeof PainelForumInternoThreadIdRoute
  '/painel/forum/$threadId': typeof PainelForumThreadIdRoute
  '/painel/provas/$examId': typeof PainelProvasExamIdRoute
  '/painel/tarefas/$assignmentId': typeof PainelTarefasAssignmentIdRoute
  '/portal/apostilas/$materialId': typeof PortalApostilasMaterialIdRoute
  '/portal/biblioteca/$bookId': typeof PortalBibliotecaBookIdRoute
  '/portal/checkin/$lessonId': typeof PortalCheckinLessonIdRoute
  '/portal/disciplinas/$disciplineId': typeof PortalDisciplinasDisciplineIdRoute
  '/portal/forum/$threadId': typeof PortalForumThreadIdRoute
  '/portal/provas/$examId': typeof PortalProvasExamIdRoute
  '/portal/tarefas/$assignmentId': typeof PortalTarefasAssignmentIdRoute
  '/painel/forum-interno': typeof PainelForumInternoIndexRoute
  '/painel/forum': typeof PainelForumIndexRoute
  '/painel/provas': typeof PainelProvasIndexRoute
  '/painel/tarefas': typeof PainelTarefasIndexRoute
  '/portal/apostilas': typeof PortalApostilasIndexRoute
  '/portal/biblioteca': typeof PortalBibliotecaIndexRoute
  '/portal/disciplinas': typeof PortalDisciplinasIndexRoute
  '/portal/forum': typeof PortalForumIndexRoute
  '/portal/provas': typeof PortalProvasIndexRoute
  '/portal/tarefas': typeof PortalTarefasIndexRoute
  '/painel/pagamentos/$chargeId/recibo': typeof PainelPagamentosChargeIdReciboRoute
  '/painel/relatorio/$studentId/pdf': typeof PainelRelatorioStudentIdPdfRoute
  '/portal/mensalidades/$chargeId/recibo': typeof PortalMensalidadesChargeIdReciboRoute
  '/painel/relatorio/turma/$disciplineId/pdf': typeof PainelRelatorioTurmaDisciplineIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/agenda.ics': typeof AgendaDoticsRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/esqueci-senha-aluno': typeof EsqueciSenhaAlunoRoute
  '/login': typeof LoginRoute
  '/login-aluno': typeof LoginAlunoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/redefinir-senha-aluno': typeof RedefinirSenhaAlunoRoute
  '/painel/agenda': typeof PainelAgendaRoute
  '/painel/alunos': typeof PainelAlunosRoute
  '/painel/auditoria': typeof PainelAuditoriaRoute
  '/painel/biblioteca': typeof PainelBibliotecaRoute
  '/painel/despesas': typeof PainelDespesasRoute
  '/painel/financeiro': typeof PainelFinanceiroRoute
  '/painel/materiais': typeof PainelMateriaisRoute
  '/painel/pagamentos': typeof PainelPagamentosRouteWithChildren
  '/painel/professores': typeof PainelProfessoresRoute
  '/painel/relatorio': typeof PainelRelatorioRouteWithChildren
  '/painel/relatorio-modulo': typeof PainelRelatorioModuloRoute
  '/painel/trocar-senha': typeof PainelTrocarSenhaRoute
  '/portal/conta': typeof PortalContaRoute
  '/portal/discipulado': typeof PortalDiscipuladoRoute
  '/portal/mensalidades': typeof PortalMensalidadesRouteWithChildren
  '/portal/notas': typeof PortalNotasRoute
  '/portal/pdf': typeof PortalPdfRoute
  '/portal/trocar-senha': typeof PortalTrocarSenhaRoute
  '/portal/videos': typeof PortalVideosRoute
  '/semestre/$semester': typeof SemestreSemesterRoute
  '/painel/': typeof PainelIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/api/cron/finalize-expired-exams': typeof ApiCronFinalizeExpiredExamsRoute
  '/api/cron/payment-reminders': typeof ApiCronPaymentRemindersRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
  '/painel/disciplinas/$disciplineId': typeof PainelDisciplinasDisciplineIdRoute
  '/painel/forum-interno/$threadId': typeof PainelForumInternoThreadIdRoute
  '/painel/forum/$threadId': typeof PainelForumThreadIdRoute
  '/painel/provas/$examId': typeof PainelProvasExamIdRoute
  '/painel/tarefas/$assignmentId': typeof PainelTarefasAssignmentIdRoute
  '/portal/apostilas/$materialId': typeof PortalApostilasMaterialIdRoute
  '/portal/biblioteca/$bookId': typeof PortalBibliotecaBookIdRoute
  '/portal/checkin/$lessonId': typeof PortalCheckinLessonIdRoute
  '/portal/disciplinas/$disciplineId': typeof PortalDisciplinasDisciplineIdRoute
  '/portal/forum/$threadId': typeof PortalForumThreadIdRoute
  '/portal/provas/$examId': typeof PortalProvasExamIdRoute
  '/portal/tarefas/$assignmentId': typeof PortalTarefasAssignmentIdRoute
  '/painel/forum-interno/': typeof PainelForumInternoIndexRoute
  '/painel/forum/': typeof PainelForumIndexRoute
  '/painel/provas/': typeof PainelProvasIndexRoute
  '/painel/tarefas/': typeof PainelTarefasIndexRoute
  '/portal/apostilas/': typeof PortalApostilasIndexRoute
  '/portal/biblioteca/': typeof PortalBibliotecaIndexRoute
  '/portal/disciplinas/': typeof PortalDisciplinasIndexRoute
  '/portal/forum/': typeof PortalForumIndexRoute
  '/portal/provas/': typeof PortalProvasIndexRoute
  '/portal/tarefas/': typeof PortalTarefasIndexRoute
  '/painel/pagamentos/$chargeId/recibo': typeof PainelPagamentosChargeIdReciboRoute
  '/painel/relatorio/$studentId/pdf': typeof PainelRelatorioStudentIdPdfRoute
  '/portal/mensalidades/$chargeId/recibo': typeof PortalMensalidadesChargeIdReciboRoute
  '/painel/relatorio/turma/$disciplineId/pdf': typeof PainelRelatorioTurmaDisciplineIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/portal'
    | '/agenda.ics'
    | '/confirmar-email'
    | '/esqueci-senha'
    | '/esqueci-senha-aluno'
    | '/login'
    | '/login-aluno'
    | '/redefinir-senha'
    | '/redefinir-senha-aluno'
    | '/painel/agenda'
    | '/painel/alunos'
    | '/painel/auditoria'
    | '/painel/biblioteca'
    | '/painel/despesas'
    | '/painel/financeiro'
    | '/painel/materiais'
    | '/painel/pagamentos'
    | '/painel/professores'
    | '/painel/relatorio'
    | '/painel/relatorio-modulo'
    | '/painel/trocar-senha'
    | '/portal/conta'
    | '/portal/discipulado'
    | '/portal/mensalidades'
    | '/portal/notas'
    | '/portal/pdf'
    | '/portal/trocar-senha'
    | '/portal/videos'
    | '/semestre/$semester'
    | '/painel/'
    | '/portal/'
    | '/api/blob/upload'
    | '/api/cron/finalize-expired-exams'
    | '/api/cron/payment-reminders'
    | '/api/mercadopago/webhook'
    | '/painel/disciplinas/$disciplineId'
    | '/painel/forum-interno/$threadId'
    | '/painel/forum/$threadId'
    | '/painel/provas/$examId'
    | '/painel/tarefas/$assignmentId'
    | '/portal/apostilas/$materialId'
    | '/portal/biblioteca/$bookId'
    | '/portal/checkin/$lessonId'
    | '/portal/disciplinas/$disciplineId'
    | '/portal/forum/$threadId'
    | '/portal/provas/$examId'
    | '/portal/tarefas/$assignmentId'
    | '/painel/forum-interno/'
    | '/painel/forum/'
    | '/painel/provas/'
    | '/painel/tarefas/'
    | '/portal/apostilas/'
    | '/portal/biblioteca/'
    | '/portal/disciplinas/'
    | '/portal/forum/'
    | '/portal/provas/'
    | '/portal/tarefas/'
    | '/painel/pagamentos/$chargeId/recibo'
    | '/painel/relatorio/$studentId/pdf'
    | '/portal/mensalidades/$chargeId/recibo'
    | '/painel/relatorio/turma/$disciplineId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda.ics'
    | '/confirmar-email'
    | '/esqueci-senha'
    | '/esqueci-senha-aluno'
    | '/login'
    | '/login-aluno'
    | '/redefinir-senha'
    | '/redefinir-senha-aluno'
    | '/painel/agenda'
    | '/painel/alunos'
    | '/painel/auditoria'
    | '/painel/biblioteca'
    | '/painel/despesas'
    | '/painel/financeiro'
    | '/painel/materiais'
    | '/painel/pagamentos'
    | '/painel/professores'
    | '/painel/relatorio'
    | '/painel/relatorio-modulo'
    | '/painel/trocar-senha'
    | '/portal/conta'
    | '/portal/discipulado'
    | '/portal/mensalidades'
    | '/portal/notas'
    | '/portal/pdf'
    | '/portal/trocar-senha'
    | '/portal/videos'
    | '/semestre/$semester'
    | '/painel'
    | '/portal'
    | '/api/blob/upload'
    | '/api/cron/finalize-expired-exams'
    | '/api/cron/payment-reminders'
    | '/api/mercadopago/webhook'
    | '/painel/disciplinas/$disciplineId'
    | '/painel/forum-interno/$threadId'
    | '/painel/forum/$threadId'
    | '/painel/provas/$examId'
    | '/painel/tarefas/$assignmentId'
    | '/portal/apostilas/$materialId'
    | '/portal/biblioteca/$bookId'
    | '/portal/checkin/$lessonId'
    | '/portal/disciplinas/$disciplineId'
    | '/portal/forum/$threadId'
    | '/portal/provas/$examId'
    | '/portal/tarefas/$assignmentId'
    | '/painel/forum-interno'
    | '/painel/forum'
    | '/painel/provas'
    | '/painel/tarefas'
    | '/portal/apostilas'
    | '/portal/biblioteca'
    | '/portal/disciplinas'
    | '/portal/forum'
    | '/portal/provas'
    | '/portal/tarefas'
    | '/painel/pagamentos/$chargeId/recibo'
    | '/painel/relatorio/$studentId/pdf'
    | '/portal/mensalidades/$chargeId/recibo'
    | '/painel/relatorio/turma/$disciplineId/pdf'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/portal'
    | '/agenda.ics'
    | '/confirmar-email'
    | '/esqueci-senha'
    | '/esqueci-senha-aluno'
    | '/login'
    | '/login-aluno'
    | '/redefinir-senha'
    | '/redefinir-senha-aluno'
    | '/painel/agenda'
    | '/painel/alunos'
    | '/painel/auditoria'
    | '/painel/biblioteca'
    | '/painel/despesas'
    | '/painel/financeiro'
    | '/painel/materiais'
    | '/painel/pagamentos'
    | '/painel/professores'
    | '/painel/relatorio'
    | '/painel/relatorio-modulo'
    | '/painel/trocar-senha'
    | '/portal/conta'
    | '/portal/discipulado'
    | '/portal/mensalidades'
    | '/portal/notas'
    | '/portal/pdf'
    | '/portal/trocar-senha'
    | '/portal/videos'
    | '/semestre/$semester'
    | '/painel/'
    | '/portal/'
    | '/api/blob/upload'
    | '/api/cron/finalize-expired-exams'
    | '/api/cron/payment-reminders'
    | '/api/mercadopago/webhook'
    | '/painel/disciplinas/$disciplineId'
    | '/painel/forum-interno/$threadId'
    | '/painel/forum/$threadId'
    | '/painel/provas/$examId'
    | '/painel/tarefas/$assignmentId'
    | '/portal/apostilas/$materialId'
    | '/portal/biblioteca/$bookId'
    | '/portal/checkin/$lessonId'
    | '/portal/disciplinas/$disciplineId'
    | '/portal/forum/$threadId'
    | '/portal/provas/$examId'
    | '/portal/tarefas/$assignmentId'
    | '/painel/forum-interno/'
    | '/painel/forum/'
    | '/painel/provas/'
    | '/painel/tarefas/'
    | '/portal/apostilas/'
    | '/portal/biblioteca/'
    | '/portal/disciplinas/'
    | '/portal/forum/'
    | '/portal/provas/'
    | '/portal/tarefas/'
    | '/painel/pagamentos/$chargeId/recibo'
    | '/painel/relatorio/$studentId/pdf'
    | '/portal/mensalidades/$chargeId/recibo'
    | '/painel/relatorio/turma/$disciplineId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AgendaDoticsRoute: typeof AgendaDoticsRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  EsqueciSenhaAlunoRoute: typeof EsqueciSenhaAlunoRoute
  LoginRoute: typeof LoginRoute
  LoginAlunoRoute: typeof LoginAlunoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RedefinirSenhaAlunoRoute: typeof RedefinirSenhaAlunoRoute
  SemestreSemesterRoute: typeof SemestreSemesterRoute
  ApiBlobUploadRoute: typeof ApiBlobUploadRoute
  ApiCronFinalizeExpiredExamsRoute: typeof ApiCronFinalizeExpiredExamsRoute
  ApiCronPaymentRemindersRoute: typeof ApiCronPaymentRemindersRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha-aluno': {
      id: '/redefinir-senha-aluno'
      path: '/redefinir-senha-aluno'
      fullPath: '/redefinir-senha-aluno'
      preLoaderRoute: typeof RedefinirSenhaAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-aluno': {
      id: '/login-aluno'
      path: '/login-aluno'
      fullPath: '/login-aluno'
      preLoaderRoute: typeof LoginAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha-aluno': {
      id: '/esqueci-senha-aluno'
      path: '/esqueci-senha-aluno'
      fullPath: '/esqueci-senha-aluno'
      preLoaderRoute: typeof EsqueciSenhaAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda.ics': {
      id: '/agenda.ics'
      path: '/agenda.ics'
      fullPath: '/agenda.ics'
      preLoaderRoute: typeof AgendaDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/semestre/$semester': {
      id: '/semestre/$semester'
      path: '/semestre/$semester'
      fullPath: '/semestre/$semester'
      preLoaderRoute: typeof SemestreSemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/videos': {
      id: '/portal/videos'
      path: '/videos'
      fullPath: '/portal/videos'
      preLoaderRoute: typeof PortalVideosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/trocar-senha': {
      id: '/portal/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/portal/trocar-senha'
      preLoaderRoute: typeof PortalTrocarSenhaRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/pdf': {
      id: '/portal/pdf'
      path: '/pdf'
      fullPath: '/portal/pdf'
      preLoaderRoute: typeof PortalPdfRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/notas': {
      id: '/portal/notas'
      path: '/notas'
      fullPath: '/portal/notas'
      preLoaderRoute: typeof PortalNotasRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/mensalidades': {
      id: '/portal/mensalidades'
      path: '/mensalidades'
      fullPath: '/portal/mensalidades'
      preLoaderRoute: typeof PortalMensalidadesRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/discipulado': {
      id: '/portal/discipulado'
      path: '/discipulado'
      fullPath: '/portal/discipulado'
      preLoaderRoute: typeof PortalDiscipuladoRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/conta': {
      id: '/portal/conta'
      path: '/conta'
      fullPath: '/portal/conta'
      preLoaderRoute: typeof PortalContaRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/painel/trocar-senha': {
      id: '/painel/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/painel/trocar-senha'
      preLoaderRoute: typeof PainelTrocarSenhaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/relatorio-modulo': {
      id: '/painel/relatorio-modulo'
      path: '/relatorio-modulo'
      fullPath: '/painel/relatorio-modulo'
      preLoaderRoute: typeof PainelRelatorioModuloRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/relatorio': {
      id: '/painel/relatorio'
      path: '/relatorio'
      fullPath: '/painel/relatorio'
      preLoaderRoute: typeof PainelRelatorioRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/professores': {
      id: '/painel/professores'
      path: '/professores'
      fullPath: '/painel/professores'
      preLoaderRoute: typeof PainelProfessoresRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/pagamentos': {
      id: '/painel/pagamentos'
      path: '/pagamentos'
      fullPath: '/painel/pagamentos'
      preLoaderRoute: typeof PainelPagamentosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/materiais': {
      id: '/painel/materiais'
      path: '/materiais'
      fullPath: '/painel/materiais'
      preLoaderRoute: typeof PainelMateriaisRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/financeiro': {
      id: '/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof PainelFinanceiroRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/despesas': {
      id: '/painel/despesas'
      path: '/despesas'
      fullPath: '/painel/despesas'
      preLoaderRoute: typeof PainelDespesasRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/biblioteca': {
      id: '/painel/biblioteca'
      path: '/biblioteca'
      fullPath: '/painel/biblioteca'
      preLoaderRoute: typeof PainelBibliotecaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/auditoria': {
      id: '/painel/auditoria'
      path: '/auditoria'
      fullPath: '/painel/auditoria'
      preLoaderRoute: typeof PainelAuditoriaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/alunos': {
      id: '/painel/alunos'
      path: '/alunos'
      fullPath: '/painel/alunos'
      preLoaderRoute: typeof PainelAlunosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/agenda': {
      id: '/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/portal/tarefas/': {
      id: '/portal/tarefas/'
      path: '/tarefas'
      fullPath: '/portal/tarefas/'
      preLoaderRoute: typeof PortalTarefasIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/provas/': {
      id: '/portal/provas/'
      path: '/provas'
      fullPath: '/portal/provas/'
      preLoaderRoute: typeof PortalProvasIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/forum/': {
      id: '/portal/forum/'
      path: '/forum'
      fullPath: '/portal/forum/'
      preLoaderRoute: typeof PortalForumIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/disciplinas/': {
      id: '/portal/disciplinas/'
      path: '/disciplinas'
      fullPath: '/portal/disciplinas/'
      preLoaderRoute: typeof PortalDisciplinasIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/biblioteca/': {
      id: '/portal/biblioteca/'
      path: '/biblioteca'
      fullPath: '/portal/biblioteca/'
      preLoaderRoute: typeof PortalBibliotecaIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/apostilas/': {
      id: '/portal/apostilas/'
      path: '/apostilas'
      fullPath: '/portal/apostilas/'
      preLoaderRoute: typeof PortalApostilasIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/painel/tarefas/': {
      id: '/painel/tarefas/'
      path: '/tarefas'
      fullPath: '/painel/tarefas/'
      preLoaderRoute: typeof PainelTarefasIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/provas/': {
      id: '/painel/provas/'
      path: '/provas'
      fullPath: '/painel/provas/'
      preLoaderRoute: typeof PainelProvasIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/forum/': {
      id: '/painel/forum/'
      path: '/forum'
      fullPath: '/painel/forum/'
      preLoaderRoute: typeof PainelForumIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/forum-interno/': {
      id: '/painel/forum-interno/'
      path: '/forum-interno'
      fullPath: '/painel/forum-interno/'
      preLoaderRoute: typeof PainelForumInternoIndexRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/portal/tarefas/$assignmentId': {
      id: '/portal/tarefas/$assignmentId'
      path: '/tarefas/$assignmentId'
      fullPath: '/portal/tarefas/$assignmentId'
      preLoaderRoute: typeof PortalTarefasAssignmentIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/provas/$examId': {
      id: '/portal/provas/$examId'
      path: '/provas/$examId'
      fullPath: '/portal/provas/$examId'
      preLoaderRoute: typeof PortalProvasExamIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/forum/$threadId': {
      id: '/portal/forum/$threadId'
      path: '/forum/$threadId'
      fullPath: '/portal/forum/$threadId'
      preLoaderRoute: typeof PortalForumThreadIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/disciplinas/$disciplineId': {
      id: '/portal/disciplinas/$disciplineId'
      path: '/disciplinas/$disciplineId'
      fullPath: '/portal/disciplinas/$disciplineId'
      preLoaderRoute: typeof PortalDisciplinasDisciplineIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/checkin/$lessonId': {
      id: '/portal/checkin/$lessonId'
      path: '/checkin/$lessonId'
      fullPath: '/portal/checkin/$lessonId'
      preLoaderRoute: typeof PortalCheckinLessonIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/biblioteca/$bookId': {
      id: '/portal/biblioteca/$bookId'
      path: '/biblioteca/$bookId'
      fullPath: '/portal/biblioteca/$bookId'
      preLoaderRoute: typeof PortalBibliotecaBookIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/apostilas/$materialId': {
      id: '/portal/apostilas/$materialId'
      path: '/apostilas/$materialId'
      fullPath: '/portal/apostilas/$materialId'
      preLoaderRoute: typeof PortalApostilasMaterialIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/painel/tarefas/$assignmentId': {
      id: '/painel/tarefas/$assignmentId'
      path: '/tarefas/$assignmentId'
      fullPath: '/painel/tarefas/$assignmentId'
      preLoaderRoute: typeof PainelTarefasAssignmentIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/provas/$examId': {
      id: '/painel/provas/$examId'
      path: '/provas/$examId'
      fullPath: '/painel/provas/$examId'
      preLoaderRoute: typeof PainelProvasExamIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/forum/$threadId': {
      id: '/painel/forum/$threadId'
      path: '/forum/$threadId'
      fullPath: '/painel/forum/$threadId'
      preLoaderRoute: typeof PainelForumThreadIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/forum-interno/$threadId': {
      id: '/painel/forum-interno/$threadId'
      path: '/forum-interno/$threadId'
      fullPath: '/painel/forum-interno/$threadId'
      preLoaderRoute: typeof PainelForumInternoThreadIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/disciplinas/$disciplineId': {
      id: '/painel/disciplinas/$disciplineId'
      path: '/disciplinas/$disciplineId'
      fullPath: '/painel/disciplinas/$disciplineId'
      preLoaderRoute: typeof PainelDisciplinasDisciplineIdRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/payment-reminders': {
      id: '/api/cron/payment-reminders'
      path: '/api/cron/payment-reminders'
      fullPath: '/api/cron/payment-reminders'
      preLoaderRoute: typeof ApiCronPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/finalize-expired-exams': {
      id: '/api/cron/finalize-expired-exams'
      path: '/api/cron/finalize-expired-exams'
      fullPath: '/api/cron/finalize-expired-exams'
      preLoaderRoute: typeof ApiCronFinalizeExpiredExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/upload': {
      id: '/api/blob/upload'
      path: '/api/blob/upload'
      fullPath: '/api/blob/upload'
      preLoaderRoute: typeof ApiBlobUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/mensalidades/$chargeId/recibo': {
      id: '/portal/mensalidades/$chargeId/recibo'
      path: '/$chargeId/recibo'
      fullPath: '/portal/mensalidades/$chargeId/recibo'
      preLoaderRoute: typeof PortalMensalidadesChargeIdReciboRouteImport
      parentRoute: typeof PortalMensalidadesRoute
    }
    '/painel/relatorio/$studentId/pdf': {
      id: '/painel/relatorio/$studentId/pdf'
      path: '/$studentId/pdf'
      fullPath: '/painel/relatorio/$studentId/pdf'
      preLoaderRoute: typeof PainelRelatorioStudentIdPdfRouteImport
      parentRoute: typeof PainelRelatorioRoute
    }
    '/painel/pagamentos/$chargeId/recibo': {
      id: '/painel/pagamentos/$chargeId/recibo'
      path: '/$chargeId/recibo'
      fullPath: '/painel/pagamentos/$chargeId/recibo'
      preLoaderRoute: typeof PainelPagamentosChargeIdReciboRouteImport
      parentRoute: typeof PainelPagamentosRoute
    }
    '/painel/relatorio/turma/$disciplineId/pdf': {
      id: '/painel/relatorio/turma/$disciplineId/pdf'
      path: '/turma/$disciplineId/pdf'
      fullPath: '/painel/relatorio/turma/$disciplineId/pdf'
      preLoaderRoute: typeof PainelRelatorioTurmaDisciplineIdPdfRouteImport
      parentRoute: typeof PainelRelatorioRoute
    }
  }
}

interface PainelPagamentosRouteChildren {
  PainelPagamentosChargeIdReciboRoute: typeof PainelPagamentosChargeIdReciboRoute
}

const PainelPagamentosRouteChildren: PainelPagamentosRouteChildren = {
  PainelPagamentosChargeIdReciboRoute: PainelPagamentosChargeIdReciboRoute,
}

const PainelPagamentosRouteWithChildren =
  PainelPagamentosRoute._addFileChildren(PainelPagamentosRouteChildren)

interface PainelRelatorioRouteChildren {
  PainelRelatorioStudentIdPdfRoute: typeof PainelRelatorioStudentIdPdfRoute
  PainelRelatorioTurmaDisciplineIdPdfRoute: typeof PainelRelatorioTurmaDisciplineIdPdfRoute
}

const PainelRelatorioRouteChildren: PainelRelatorioRouteChildren = {
  PainelRelatorioStudentIdPdfRoute: PainelRelatorioStudentIdPdfRoute,
  PainelRelatorioTurmaDisciplineIdPdfRoute:
    PainelRelatorioTurmaDisciplineIdPdfRoute,
}

const PainelRelatorioRouteWithChildren = PainelRelatorioRoute._addFileChildren(
  PainelRelatorioRouteChildren,
)

interface PainelRouteRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelAlunosRoute: typeof PainelAlunosRoute
  PainelAuditoriaRoute: typeof PainelAuditoriaRoute
  PainelBibliotecaRoute: typeof PainelBibliotecaRoute
  PainelDespesasRoute: typeof PainelDespesasRoute
  PainelFinanceiroRoute: typeof PainelFinanceiroRoute
  PainelMateriaisRoute: typeof PainelMateriaisRoute
  PainelPagamentosRoute: typeof PainelPagamentosRouteWithChildren
  PainelProfessoresRoute: typeof PainelProfessoresRoute
  PainelRelatorioRoute: typeof PainelRelatorioRouteWithChildren
  PainelRelatorioModuloRoute: typeof PainelRelatorioModuloRoute
  PainelTrocarSenhaRoute: typeof PainelTrocarSenhaRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelDisciplinasDisciplineIdRoute: typeof PainelDisciplinasDisciplineIdRoute
  PainelForumInternoThreadIdRoute: typeof PainelForumInternoThreadIdRoute
  PainelForumThreadIdRoute: typeof PainelForumThreadIdRoute
  PainelProvasExamIdRoute: typeof PainelProvasExamIdRoute
  PainelTarefasAssignmentIdRoute: typeof PainelTarefasAssignmentIdRoute
  PainelForumInternoIndexRoute: typeof PainelForumInternoIndexRoute
  PainelForumIndexRoute: typeof PainelForumIndexRoute
  PainelProvasIndexRoute: typeof PainelProvasIndexRoute
  PainelTarefasIndexRoute: typeof PainelTarefasIndexRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelAlunosRoute: PainelAlunosRoute,
  PainelAuditoriaRoute: PainelAuditoriaRoute,
  PainelBibliotecaRoute: PainelBibliotecaRoute,
  PainelDespesasRoute: PainelDespesasRoute,
  PainelFinanceiroRoute: PainelFinanceiroRoute,
  PainelMateriaisRoute: PainelMateriaisRoute,
  PainelPagamentosRoute: PainelPagamentosRouteWithChildren,
  PainelProfessoresRoute: PainelProfessoresRoute,
  PainelRelatorioRoute: PainelRelatorioRouteWithChildren,
  PainelRelatorioModuloRoute: PainelRelatorioModuloRoute,
  PainelTrocarSenhaRoute: PainelTrocarSenhaRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelDisciplinasDisciplineIdRoute: PainelDisciplinasDisciplineIdRoute,
  PainelForumInternoThreadIdRoute: PainelForumInternoThreadIdRoute,
  PainelForumThreadIdRoute: PainelForumThreadIdRoute,
  PainelProvasExamIdRoute: PainelProvasExamIdRoute,
  PainelTarefasAssignmentIdRoute: PainelTarefasAssignmentIdRoute,
  PainelForumInternoIndexRoute: PainelForumInternoIndexRoute,
  PainelForumIndexRoute: PainelForumIndexRoute,
  PainelProvasIndexRoute: PainelProvasIndexRoute,
  PainelTarefasIndexRoute: PainelTarefasIndexRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

interface PortalMensalidadesRouteChildren {
  PortalMensalidadesChargeIdReciboRoute: typeof PortalMensalidadesChargeIdReciboRoute
}

const PortalMensalidadesRouteChildren: PortalMensalidadesRouteChildren = {
  PortalMensalidadesChargeIdReciboRoute: PortalMensalidadesChargeIdReciboRoute,
}

const PortalMensalidadesRouteWithChildren =
  PortalMensalidadesRoute._addFileChildren(PortalMensalidadesRouteChildren)

interface PortalRouteRouteChildren {
  PortalContaRoute: typeof PortalContaRoute
  PortalDiscipuladoRoute: typeof PortalDiscipuladoRoute
  PortalMensalidadesRoute: typeof PortalMensalidadesRouteWithChildren
  PortalNotasRoute: typeof PortalNotasRoute
  PortalPdfRoute: typeof PortalPdfRoute
  PortalTrocarSenhaRoute: typeof PortalTrocarSenhaRoute
  PortalVideosRoute: typeof PortalVideosRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalApostilasMaterialIdRoute: typeof PortalApostilasMaterialIdRoute
  PortalBibliotecaBookIdRoute: typeof PortalBibliotecaBookIdRoute
  PortalCheckinLessonIdRoute: typeof PortalCheckinLessonIdRoute
  PortalDisciplinasDisciplineIdRoute: typeof PortalDisciplinasDisciplineIdRoute
  PortalForumThreadIdRoute: typeof PortalForumThreadIdRoute
  PortalProvasExamIdRoute: typeof PortalProvasExamIdRoute
  PortalTarefasAssignmentIdRoute: typeof PortalTarefasAssignmentIdRoute
  PortalApostilasIndexRoute: typeof PortalApostilasIndexRoute
  PortalBibliotecaIndexRoute: typeof PortalBibliotecaIndexRoute
  PortalDisciplinasIndexRoute: typeof PortalDisciplinasIndexRoute
  PortalForumIndexRoute: typeof PortalForumIndexRoute
  PortalProvasIndexRoute: typeof PortalProvasIndexRoute
  PortalTarefasIndexRoute: typeof PortalTarefasIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalContaRoute: PortalContaRoute,
  PortalDiscipuladoRoute: PortalDiscipuladoRoute,
  PortalMensalidadesRoute: PortalMensalidadesRouteWithChildren,
  PortalNotasRoute: PortalNotasRoute,
  PortalPdfRoute: PortalPdfRoute,
  PortalTrocarSenhaRoute: PortalTrocarSenhaRoute,
  PortalVideosRoute: PortalVideosRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalApostilasMaterialIdRoute: PortalApostilasMaterialIdRoute,
  PortalBibliotecaBookIdRoute: PortalBibliotecaBookIdRoute,
  PortalCheckinLessonIdRoute: PortalCheckinLessonIdRoute,
  PortalDisciplinasDisciplineIdRoute: PortalDisciplinasDisciplineIdRoute,
  PortalForumThreadIdRoute: PortalForumThreadIdRoute,
  PortalProvasExamIdRoute: PortalProvasExamIdRoute,
  PortalTarefasAssignmentIdRoute: PortalTarefasAssignmentIdRoute,
  PortalApostilasIndexRoute: PortalApostilasIndexRoute,
  PortalBibliotecaIndexRoute: PortalBibliotecaIndexRoute,
  PortalDisciplinasIndexRoute: PortalDisciplinasIndexRoute,
  PortalForumIndexRoute: PortalForumIndexRoute,
  PortalProvasIndexRoute: PortalProvasIndexRoute,
  PortalTarefasIndexRoute: PortalTarefasIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AgendaDoticsRoute: AgendaDoticsRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  EsqueciSenhaAlunoRoute: EsqueciSenhaAlunoRoute,
  LoginRoute: LoginRoute,
  LoginAlunoRoute: LoginAlunoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RedefinirSenhaAlunoRoute: RedefinirSenhaAlunoRoute,
  SemestreSemesterRoute: SemestreSemesterRoute,
  ApiBlobUploadRoute: ApiBlobUploadRoute,
  ApiCronFinalizeExpiredExamsRoute: ApiCronFinalizeExpiredExamsRoute,
  ApiCronPaymentRemindersRoute: ApiCronPaymentRemindersRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
